### ISSUE TITLE
Latest releases can't successfully add Apple Lossless audio passthru track

### ISSUE THREAD

**Issue by ghender3** [SublerApp/Subler#10]
Release 1.7.5 (and earlier releases I used in the past) allowed importing ALAC audio as a passthru track. Releases 1.8 and 1.8.1 import the track, but the resulting video .mp4, in MediaInfo, shows only that there is an ALAC track - no other information. But neither VLC nor MacOS TV can detect its presence. 

Release 1.8.2 again, in MediaInfo, shows that there is an ALAC track with no other information, and VLC detects its presence, but gives an error message if you try to select it.

**Comment by galad87** [comment]
Another copy & paste gone wrong, fixed in https://github.com/SublerApp/mp4v2/commit/8920d20cf8d75feaf328b3fba089c5b53284f6f5

I'll make a new release soon.

**Comment by galad87** [comment]
The fix is available in https://github.com/SublerApp/Subler/releases/tag/1.8.3
