### ISSUE TITLE
copy and paste tags broken from 1.8.2 to 1.8.3

### ISSUE THREAD

**Issue by dobratzp** [SublerApp/Subler#12]
I often create new files just to copy some of the tags into the movie file.

Select 1 or more lines of metadata from one file, press command + C then switch to another file and select command + V.

The paste operation does not seem to have any effect in Subler 1.8.3 (worked in version 1.8.2 and earlier).

Pasting into a text editor shows the tags as plain text, so the copy function is working as before.

To workaround, I use the sets feature.  Have to delete all the tags that I don't want to copy and then create a set to apply to the other file.  Then I have to go into settings and delete the set.

**Comment by galad87** [comment]
I noticed a few minutes after I made the new release yesterday 😅, I am modernizing some parts of the codebase and unfortunately introduced a couple of regressions too.

**Comment by galad87** [comment]
Fixed in 1.8.4
