### ISSUE TITLE
Mistagging episodes

### ISSUE THREAD

**Issue by bggolding** [SublerApp/Subler#13]
I was trying to use Subler to tag episodes of "Veep". Initially I added them to the queue but when I looked at the resulting files, it had tagged them as "The Deep", a cartoon show.

When I tried doing the files individually, the same thing happened. I'll attach a screen shot.

I was able to get them to tag correctly by removing the "(2012)" from the title but should that have been necessary?

<img width="696" alt="image" src="https://github.com/user-attachments/assets/00349f3d-0942-41e2-aa93-78a46464709f">

**Comment by galad87** [comment]
Matching movies and tv shows by names will always be an imperfect science. Subler send the tv show title to the metadata provider api, and gets the results back.
If TheTVDB returns "The Deep" as the first result for "Veep (2012)", there is no good way to fix on Subler side.
