### ISSUE TITLE
(1.8.4) FLAC audio not being added/converted to AAC 

### ISSUE THREAD

**Issue by tvjctr** [SublerApp/Subler#14]
I add some 2 ch FLAC audio tracks  and select AAC-Stereo as the conversion, but the resulting file doesn't contain any audio tracks, only the video.

EDIT: FLAC support seems to have been broken starting with version 1.8.  (It works fine in 1.7.5).

**Comment by galad87** [comment]
Is the source file a .flac file or something else?

**Comment by tvjctr** [comment]
It doesn't work on .mkv with video and audio.  It also doesn't work if I separately drag .flac files.  They are added to the media list, but after saving they disappear from the list and the resulting mp4 has no audio. 

Another observation.  Under 1.7.5, when I drag a separate .flac file, I am given the option to convert different AAC formats (Stereo, Mono, Multi-Channel, etc...).  But when I drag a separate file under 1.8.3, I am not given this option.  The "Action" column is greyed out and listed as Passthru" and I can not select any AAC format.  When I click add, the .flac files are added to the media list, but as flac, 2 ch.  But again, when I save, the resulting file has no audio.

**Comment by eddiewong396** [comment]
I have a mkv file with AAC but when I tried saving it to mp4, the audio tracks are missing. I'm using version 1.8.4.

**Comment by galad87** [comment]
Did .flac files ever work? Anyway it should be fixed in https://github.com/SublerApp/MP42Foundation/commit/b85f5d59e2686bf74014f72b311cdf8a19101122 , I'll make a new release in the next few days.

**Comment by tvjctr** [comment]
Yeah, .flac files work with 1.7.5 when converting to AAC.  Of course you cant save a FLAC stream into the container (yet), but that is expected.  Thanks for the fix-up... will wait patiently for the new release.

**Comment by galad87** [comment]
What version of macOS are you using? Importing from .flac files didn't work for me on macOS 13 and 14.

**Comment by tvjctr** [comment]
You're right!

.flac files didn't work on 1.7.5.  I must have forgotten to uncheck the FLAC audio tracks from the .mkv file and mistakenly thought it had converted the dragged on .flac files.  The .flac files are added to the media list, and I can select the conversion, but the saved .mp4 does not contain an AAC converted stream, the behavior is the same for 1.7.5 and 1.8.4.

Very sorry for running you through a rat race!

**Comment by galad87** [comment]
1.8.5 contains the fix.

**Comment by tvjctr** [comment]
Awesome!  Works perfectly, even with dragged .flac files.  Thank you so much for the fix and enhanced operation!
