### ISSUE TITLE
File name is not automatically changed to movie/show/episode title

### ISSUE THREAD

**Issue by Klaes1999** [SublerApp/Subler#15]
Subler used to update the filename to match the title of the movie, etc., but it no longer does that. I've looked through my settings, and everything is as it was and should be.

*Edit*
To make sure I'm understood:

I used to be able to open a file with a random name like "02jklsdhfviudhb.mp4" in Subler and add the right metadata. As soon as Subler was done with the file, it was appropriately named after the show or movie. My issue is that it no longer does this and my files come out unchanged.

**Comment by galad87** [comment]
It never did for existing files, only when it creates a new document. Probably your files were fragmented mp4 so they were imported in a new document.

**Comment by Klaes1999** [comment]
@galad87 Sorry, could you elaborate on that? For example, what is a fragmented MP4, and what do you mean it never did that for existing files? Every file I've ever run through Subler was/is an existing file. And if they were imported to a new document, I'd still have the unedited/metadata-less files on my computer, but I don't.

**Comment by galad87** [comment]
Maybe you were using the queue? There is a feature to rename the files in the queue, but there never was one for things outside the queue. I know because I have to rename the files manually too, and I wrote Subler so I am fairly sure of what's in and what's not 😅

**Comment by Klaes1999** [comment]
Yeah that's what I was talking about in my original comment: Sending files to the Queue used to rename the files to match the title in the metadata. Wait, I think I just found the right settings to fix it (I'd forgotten that the Queue had it's own settings😅)

**Comment by Klaes1999** [comment]
@galad87 No dice. Any chance you know how I might set it change automatically?

**Comment by galad87** [comment]
Sending files to Queue won't add the Queue actions, so the only way is to add files directly to the queue.
Older versions are on https://bitbucket.org/galad87/subler/downloads/ if you want to try if it actually worked in some previous release.
