### ISSUE TITLE
Artwork preview slider zoom default

### ISSUE THREAD

**Issue by sarossell** [SublerApp/Subler#16]
Would it be possible to include either a preference setting or a remembered last setting for the artwork slider value for both selecting artwork and displaying injected artwork? The older versions defaulted to 100% at least for the injected artwork. My eyesight is very poor. I have to move the slicer every time to see clearly. Thank you.

**Comment by galad87** [comment]
That's a good idea. I'll see what I can do.

**Comment by sarossell** [comment]
Much appreciated. Subler is amazing. There are just a handful o apps I use on a daily basis and Subler is one of the top 5. I tried to make a donation. Will that be enabled again in the future?

Thanks again.

-Scott :@)

**Comment by galad87** [comment]
Done.
