### ISSUE TITLE
Feature Request: SUP to SRT command

### ISSUE THREAD

**Issue by tiferrei** [SublerApp/Subler#17]
Hi there, 

Thanks for the great software! I was wondering if there was a way to directly convert SUP subtitles to SRT?

I believe I can provide an MKV with the SUP subtitles bundled in, export the file to MP4 with Subler, re-import and then export the subtitles track. However if I already have directly the SUP file, is there a way to export the SRT only?

Thank you,

Tiago

**Comment by galad87** [comment]
Not with Subler, maybe there are other apps out there that can do it, but the only way to do it with Subler is to first wrap the subtitles inside a MKV files (for example with mkvtoolnix).

**Comment by tiferrei** [comment]
Ah that's a shame, thanks for the fast reply!
