### ISSUE TITLE
Keyboard Command No Longer Works

### ISSUE THREAD

**Issue by rsalter144** [SublerApp/Subler#24]
This is the second time within a month that the keyboard shortcut command to Import Metadata Online, shift-command + m no longer works.

macOS:  14.6.1
Subler: Version 1.8.5 (1.8.5)

**Comment by galad87** [comment]
There was a macOS bug recently that might have caused this.
Try if it still happens on 14.7 or 15. Anyway there isn't much I can do about this.

**Comment by rsalter144** [comment]
Understand. Thank you.
