### ISSUE TITLE
Feature Request: In Queue, change selected audio and subtitle tracks. 

### ISSUE THREAD

**Issue by JeffroDH** [SublerApp/Subler#3]
I have a group of files where the default audio is set to German and the subtitles to French. I propose a feature where these can be changed programmatically in the queue to a preferred language, if a track with that language label exists.

I have written the code for the feature to be implemented, and have a successful build, but have been unable to figure out some of the code signing issues to allow it to run locally. Similar issues seem to be preventing me from creating a pull request.

Please forgive any messiness in the code: Last night was my first time to use XCode or the Swift language. I tried to follow the conventions I saw in the existing files. Also, I added the options down at the bottom of QueueOptions.xib. I’m sure you’ll want to move the location of the options in the UI. Again, I did my best, starting with zero experience.

I’m attaching the files I edited here.
[SublerFeature.zip](https://github.com/user-attachments/files/15567829/SublerFeature.zip)

**Comment by JeffroDH** [comment]
The files I uploaded are bugged and don't work. But I have created a branch with code that works.  I haven't quite finished getting the QueueOptions UI quite right.

**Comment by galad87** [comment]
Implemented in 2d98e11
