### ISSUE TITLE
Feature Request - Add Keyboard shortcut to None button on add artwork pane

### ISSUE THREAD

**Issue by briangoodman** [SublerApp/Subler#36]
Is it possible to add a keyboard shortcut to the None button on the add artwork pane? When I'm processing multiple files with Subler, I rely on keyboard shortcuts - Shift/Alt M to start the search, carriage return to agree the choice, but if I don't want artwork (which I normally don't), I need to resort to the mouse. The ability to press the N key to indicate none (or some other keyboard shortcut) would streamline the process.

Thanks for considering this request.

Regards, Brian

**Comment by galad87** [comment]
I guess "esc" would be good.

**Comment by galad87** [comment]
Looks like "Esc" already works.
