### ISSUE TITLE
English localisation

### ISSUE THREAD

**Issue by youngoldi** [SublerApp/Subler#42]
The English localization off Subler seams not to work - or I do not find how to change to English.
It is always spain.
I am using MacOS Sequoia 15.1- it is  set to German.
![Bildschirmfoto 2024-12-12 um 21 35 20](https://github.com/user-attachments/assets/498a5447-8add-48d1-a7ea-828708d5ba05)

**Comment by galad87** [comment]
Make sure English is after German in System Settings -> Language & Region.

**Comment by youngoldi** [comment]
Thanks - that simple !!!
 sorry for bothering you
