### ISSUE TITLE
64 bits chunk offset does not work in Subler 1.8

### ISSUE THREAD

**Issue by Tyranicus2063** [SublerApp/Subler#6]
When attempting to process a file larger than 4GB in Subler 1.8, whether the 64 bits chunk offset option is checked or not, the result is an unusable file and a dialog box warning that the 64 bits chunk offset was not enabled. This issue is not present in Subler 1.7.5 I confirmed that the same file with the same settings on the same computer is processed correctly when using that version. This was on a M2 MacBook Air running macOS Sonoma 14.5.

![Screenshot 2024-07-03 at 3 19 59 PM](https://github.com/SublerApp/Subler/assets/124219083/437ca1ed-de91-4b33-a9e6-61345a082953)
![Screenshot 2024-07-03 at 3 21 03 PM](https://github.com/SublerApp/Subler/assets/124219083/5a720f4e-665d-4ab6-84ce-f2c678a5da7d)

**Comment by irregulara** [comment]
Came here to report this exact issue. It appeared after the most recent Subler update. 

MacOS Version 13.6.7 (22G720)
iMac 3.8 GHz Quad-Core Intel Core i5
64 GB 2400 MHz DDR4

**Comment by galad87** [comment]
Should be fixed in https://github.com/SublerApp/Subler/releases/tag/1.8.1

The mp4v2 library was updated to a newer version, and there were some regressions.
