### ISSUE TITLE
New update is slow

### ISSUE THREAD

**Issue by diberu** [SublerApp/Subler#7]
With new update, Subler is a lot slower. It's stuck on "saving" for minutes when it only took 30 seconds or less to save the new file.

**Comment by galad87** [comment]
Please describe exactly what are you doing, and a file that you can share I could use to reproduce the issue would help.

**Comment by diberu** [comment]
Solved! I just unchecked "chapters preview". Thank you for your great software!

**Comment by Sydneyrooster65** [comment]
Am having the same issue. To experiment, I just changed one item on the metadata, hit command-S and it just sits there saving... for what seems like forever. Some files become completely unsupported and unplayable in Quicktime or VLC!
<img width="802" alt="Screen Shot 2024-07-06 at 9 36 31 am" src="https://github.com/SublerApp/Subler/assets/174841630/317e4659-e327-4ed8-b406-72ead877634b">

**Comment by cjenks1117** [comment]
I am having the same issue with it getting stuck on "Saving". If I wait enough, sometimes it will complete and the file will be ok and playable. If I have to hit cancel, the file becomes corrupt and unplayable.
![Screen Shot 2024-07-05 at 9 51 29 PM](https://github.com/SublerApp/Subler/assets/27376242/d619b6ea-4044-4d40-a7de-5bfa2cfd2410)

**Comment by Sydneyrooster65** [comment]
My only solution is to be patient. The file will save eventually, but it takes over five minutes to finish. That begs the question about what code has been added to lengthen this process.

**Comment by galad87** [comment]
I need a file to reproduce the issue, without I can't do anything.

**Comment by Sydneyrooster65** [comment]
https://drive.google.com/file/d/1zP944q9Jt21JrfRnMhE3_-G8iAdF30oZ/view?usp=share_link

**Comment by galad87** [comment]
Thanks, got it. I'll check what's going wrong.

**Comment by galad87** [comment]
Found the issue, a single line of code resurfaced when I merged some mp4v2 changes. I'll make a new release soon.

**Comment by galad87** [comment]
The slow save is fixed in https://github.com/SublerApp/Subler/releases/tag/1.8.2

**Comment by Sydneyrooster65** [comment]
Grazie, Amico.
